# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true 

# Setup
title:               Georgios Mavromatidis
tagline:             'A personal website'
description:         'PhD student in Urban Energy Systems at ETH Zurich'
url:                 http://mavromatidis.me
baseurl:             http://mavromatidis.me
production_url:      http://www.mavromatidis.me
paginate:            5
paginate_path:       "blog/:num"

# About/contact
author:
  name:              Georgios Mavromatidis
  url:               https://twitter.com/gmavrom
  email:             georgios.mavromatidis@gmail.com

sass:
  sass_dir: _sass
  style: :compressed

# Custom vars
version:             1.0.0

github:
repo:               https://github.com/gmavrom/gmavrom.github.io
