# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Georgios Mavromatidis
tagline:          'A Personal Website'
description:      'PhD student in Urban Energy Systems at ETH Zurich'
url:              http://lanyon.getpoole.com

author:
  name:           'Georgios Mavromatidis'
  url:            https://twitter.com/gmavrom

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gmavrom/gmavrom.github.io
