# Dependencies
markdown:         kramdown
pygments:         false

# Permalinks
permalink:        pretty

# Setup
title:            Georgios Mavromatidis
tagline:          'A Personal Website'
description:      'PhD student in Urban Energy Systems at ETH Zurich'
url:              http://mavromatidis.me

author:
  name:           'Georgios Mavromatidis'
  url:            https://twitter.com/gmavrom
  gravatar_md5:   f4d99d27a868f6337e9da141ef0d0c08

paginate:         5
paginate_path:    "blog/:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gmavrom/gmavrom.github.io
