# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true 

# Setup
title:               Georgios Mavromatidis
tagline:             'A personal website'
description:         'PhD student in Urban Energy Systems at ETH Zurich'
url:                 http://mavromatidis.me
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Georgios Mavromatidis
  url:               https://twitter.com/gmavrom
  email:             georgios.mavromatidis@gmail.com

# Custom vars
version:             1.0.0
